name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]  # Cambia a 'master' si tu rama es esa

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Firebase
        run: "firebase deploy --only hosting:mast---3-programas --token $FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
